# Generated by Django 3.0.7 on 2020-06-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('primaryid', models.AutoField(db_column='primaryid', primary_key=True, serialize=False)),
                ('director', models.CharField(db_column='director', max_length=32)),
                ('popularity', models.FloatField(blank=True, db_column='99popularity', null=True)),
                ('imdbscore', models.FloatField(blank=True, db_column='imdb_score', null=True)),
                ('name', models.CharField(db_column='name', max_length=32)),
                ('genre', models.TextField(db_column='genre', null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
